travis:
  secure:
    BINSTAR_TOKEN: MwmNfnfb4wqs7yL+jifAXeMv3/8qhBQra3pTZkplzjSrJh/7WEp+24Ki4rc6nRc6Ba+oEXLHj0TYkan4uPjM1TDQ/syQ77bDp8VzmMfV/D7ZOt6kIsjXfi/h5pqIuZAEnBoh0lpSVB3vfJQJMxjlazafn1RfsXRcLvWc+mqmG6NSidt5q/VouN5Gx7QJhpjoJ4imDXHe/fzPGFPpDxHSUtDaDIyiWZUjGCvYZ1tWGZpLHFNK24OS2mxt4aEdoBbdfNih+z2503ngMts/TuX5Luhtm3E76rL3I86EFD70jRh/PGf91VxdtP1c1HJ6yISYRX8844LJ4MbMzv5BgPXjgODe63XrO3vwNDq+23/RSeGPWKr2EJyImF0Fq0vaROBK7155TI/E9/UTFQjuDZB3pJWDveWKhvLw0DIfejIiKPJ5VVfBy0hOUhhl7Y7MgTxXf3d4aCeS/6idNIY1qMKYk5NM+sDAj9BxUX8jBNCWZNdyZMgoNW8nHbZZmoTzcfzX6ycLOcMzHOdpXvodFHuipSCJfv8I6pW70uji+ytfYEwU4pvp1yxjYRUddYMwMeG+XP9up8MMfVE3EtdYZgGsUQffgMOIJqgfKGXPAsAh4daNEXkeJO7edCR5spjhSDWZhj0iTH70RdPuyURsBFd3CRv2aIefXMjbVN3KnR18eYU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
