travis:
  secure:
    BINSTAR_TOKEN: Y0FSAFUCd93QvwcR4BOuur4feGf8jsHfOZ0L1R8SuMSgpGrHQsc4MWt0cCjlABcB7lC8+9QllVMNpbwW7h2jRApCyZlj9uczcN145JKiUNx5DpkoAW7D2AwOm2NEVzJVqg4Lc981oXiHiXPRVxix2nzCuLfJTMDO8qsQzaygP3LychvnEwRBBf2b3HhN991cN4S9xMT4MK7en9cDL+Gj7i3mPHIkbwvEieSo7GnLnovv0vWH9vy+WSMRO8xTEPTPMoy6phmRotgHuPkZ7iumHak6EQoBaPCSGX0Ydnbnmow+1EN8wl5CxF0qzu8QDywrW+jywZ5MWX8UztUtXUhPMCAnvMQuZYVyxJF5HUPAjZzzGnXDOPvEH6wj7b3/29inYaI1drEPj8O+/ydhbXW+9/f+XwwmIK+Wr4O2XM+9zxqajiKXr3DWJzBq4CCIslfLCgQYrWv9NmqBxBWoJMBL3Dp99PXDL8wOGppk6+1mftic4S3paXumo9Hrp+pMSVer1MSVxKZPUBm5Y1P6A9PnLxFyIe1qfM+MwDj4+PlS/cxg7hDctVB2ioUz1TICH5/Zcc/QyCDv0IuA17BdrUQsV/eF8oqlKj/20YmveTGXnDNglnJzgTxrpxqkfs4BGwW/ztk+yRB1K0EV62dLxhERSfIw2/i5HMkpFlxnfo8RVig=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
